# The Default Profile
[profile.default]
solc_version = "0.8.17"
auto_detect_solc = false
optimizer_runs = 999999

# Configure remappings
remappings = [
  "@ds=lib/ds-test/src/",
  "@std=lib/forge-std/src/",
  "@solbase=lib/solbase/test/"
]

[fuzz]
runs = 1_000

[profile.fuzz.ci]
runs = 100_000